services:
  - type: web
    name: splitwise-backend
    runtime: node
    buildCommand: npm install --prefix backend
    preDeployCommand: npm --prefix backend exec prisma db push -- --skip-generate --schema prisma/schema.prisma
    startCommand: npm --prefix backend start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
